### ISSUE TITLE
Add Creative Commons logos to LICENSE

### ISSUE THREAD

**Issue by onebree** [EbookFoundation/free-science-books#1]

**Comment by eshellman** [comment]
That makes sense.

**Comment by onebree** [comment]
Okay, great. I'll work on this over the weekend.

**Comment by onebree** [comment]
I just had the time to look at this issue. While editing the license, I saw that Github provides the CC0 document in a plain-text format. I decided to use that, as it also includes a link to the easy-to-read summary. The commit I am about to make will close this issue.
