### ISSUE TITLE
Transfer ownership away from org, move to awesome list

### ISSUE THREAD

**Issue by onebree** [EbookFoundation/free-science-books#11]
I just found out today that FPB is not listed under programming on the awesome list, but rather under BOOKS. I think it would be good to apply for that list, once we add more resources.

In the mean time, ownership should move to this repo's creator, rather than an organization. An org normally has multiple repos (like ruby), while we only have 1. Not saying EbookFoundation is not a great idea, but we can also transfer ownership _back_ later on.

**Comment by eshellman** [comment]
Not sure I understand about transferring ownership.

ICYMI: http://ebookfoundation.org

**Comment by onebree** [comment]
Are there other projects under ebook foundation? If so, I do not see them.

**Comment by eshellman** [comment]
the Unglue.it repos under Gluejar should gradually move here.

**Comment by onebree** [comment]
Okay, thank you. I guess I will close this issue then!
