### ISSUE TITLE
Bad or expired link: The Handbook of Essential Mathematics

### ISSUE THREAD

**Issue by bjwyman** [EbookFoundation/free-science-books#118]
I find this project interesting, and was looking over the Mathematics section. I noticed a bad/changed/expired link.

https://github.com/EbookFoundation/free-science-books/blob/e31c4f041b758333e72534d0bb0a66ddafa45de0/free-science-books.md?plain=1#L75

That is for: The Handbook of Essential Mathematics - John C. Sparks (PDF)

A search option does come up, and it is relatively easy to get to the book, but it is not clear on the best link to use for it:
- OLD/BROKEN: https://florida.theorangegrove.org/og/file/3a8c652c-11d0-e967-95fb-b5bbae2586d6/1/math_handbook.pdf
- SEARCH RESULT: https://theorangegrove.org/pdf/the-handbook-of-essential-mathematics-sparks-pdf/
- Download Link from above: https://theorangegrove.org/wp-content/uploads/2023/04/the-handbook-of-essential-mathematics-sparks.pdf-1292911.pdf

I thought I could make an attempt at a quick fix, but it was not clear which URL would be preferred for the fix.

**Comment by eshellman** [comment]
no need for a download link if you have a link to a page that has it.

**Comment by stmapman7** [comment]
@bjwyman @eshellman: I will create the PR to fix the broken link.
