### ISSUE TITLE
adding links to other lists

### ISSUE THREAD

**Issue by alcole** [EbookFoundation/free-science-books#50]
I have seen some resources that are themselves lists of links to open books. Would there be some benefit in adding the lists rather than adding the links from the list to this list?

examples include:
[https://aimath.org/textbooks/approved-textbooks/](https://aimath.org/textbooks/approved-textbooks/)
[https://www.doabooks.org/](https://www.doabooks.org/) csv of titles available here: [http://www.doabooks.org/doab?func=csv](http://www.doabooks.org/doab?func=csv)

**Comment by eshellman** [comment]
The DOAB list is heavily weighted to humanities texts.
Subject-specific lists such as the AIM list could go in the Math heading; but I worry about drawing a line between highly curated lists such as the AIM list) and thinly curated search results.

Maybe the best test is to ask whether adding an item helps someone who comes to the repo to find something "to help me learn about X".

**Comment by alcole** [comment]
thanks the the response, makes sense to me
