### ISSUE TITLE
Fluid Dynamics - Lecture Notes Broken Link

### ISSUE THREAD

**Issue by pcbock** [EbookFoundation/free-science-books#74]
The link in the Physics section for Fluid Dynamics - Lecture Notes by Shiva Prasad is not functioning at all.  It returns a 404 error.

![image](https://user-images.githubusercontent.com/11447724/96493762-61d59d00-1213-11eb-917c-02bd05b1e183.png)

**Comment by Astrodevil** [comment]
i done this recently (removed above mentioned link & listing)
